# .github/workflows/update_v2ray.yml
name: Update v2ray

on:
  repository_dispatch:
    types:
      - 'update_v2ray'
  # schedule:
  #   - cron: '*/5 * * * *'
  workflow_dispatch:
    # inputs:
    #   logLevel:
    #     description: 'test'
    #     required: true
    #     default: 'warning'
    #   tags:
    #     description: 'test'
  
    
jobs:
  
  update-v2ray:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: 'Working'
        run: 
          python3 ./main.py
      - name: config git info
        run: |
          git config --global user.email fang-yj@qq.com
          git config --global user.name fang-yj
      - name: commit
        run: |
          git checkout master
          git add .
          git commit -m "github actions 自动更新" -a
      - name: Push changes
        env:
          GITHUB_LOGIN: fang-yj
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - run: |
          git push https://$GITHUB_LOGIN:$GITHUB_TOKEN@github.com/fang-yj/test.git
      - name: done
        run: echo "done"
